-- Baseline migration: captures the schema exactly as it existed when Flyway was introduced
-- (previously managed by Hibernate's ddl-auto: update). Generated from a schema-only pg_dump
-- of the dev database, not hand-written from entity annotations, so it's byte-faithful to
-- what Hibernate actually created — including its auto-generated constraint names.
--
-- This migration is never run against the database it was captured from: see
-- spring.flyway.baseline-on-migrate / baseline-version in application.yml, which tell Flyway
-- to treat that database as already being at this version. It exists so a *fresh* database
-- (a new environment, a teammate's machine, production) can be brought to the same schema
-- from nothing, and so every schema change from here on is a new versioned migration file
-- instead of Hibernate silently altering a live database.

CREATE TABLE public.ai_usage_log (
    id bigint NOT NULL,
    count integer NOT NULL,
    date date NOT NULL,
    user_id bigint NOT NULL
);

ALTER TABLE public.ai_usage_log ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.ai_usage_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.attendance (
    id bigint NOT NULL,
    date date NOT NULL,
    status character varying(255) NOT NULL,
    student_id bigint NOT NULL,
    CONSTRAINT attendance_status_check CHECK (((status)::text = ANY ((ARRAY['PRESENT'::character varying, 'ABSENT'::character varying, 'LATE'::character varying])::text[])))
);

ALTER TABLE public.attendance ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.attendance_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.exams (
    id bigint NOT NULL,
    exam_date date NOT NULL,
    max_marks double precision NOT NULL,
    name character varying(255) NOT NULL,
    school_class_id bigint NOT NULL,
    subject_id bigint NOT NULL
);

ALTER TABLE public.exams ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.exams_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.marks (
    id bigint NOT NULL,
    marks_obtained double precision NOT NULL,
    exam_id bigint NOT NULL,
    student_id bigint NOT NULL
);

ALTER TABLE public.marks ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.marks_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.resource_views (
    id bigint NOT NULL,
    first_viewed_at timestamp(6) without time zone NOT NULL,
    last_viewed_at timestamp(6) without time zone NOT NULL,
    view_count integer NOT NULL,
    resource_id bigint NOT NULL,
    user_id bigint NOT NULL
);

ALTER TABLE public.resource_views ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.resource_views_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.resources (
    id bigint NOT NULL,
    body text NOT NULL,
    created_at timestamp(6) without time zone,
    external_url character varying(255),
    summary character varying(255) NOT NULL,
    title character varying(255) NOT NULL,
    type character varying(255) NOT NULL,
    author_id bigint NOT NULL,
    status character varying(255) NOT NULL,
    review_note character varying(255),
    CONSTRAINT resources_status_check CHECK (((status)::text = ANY ((ARRAY['DRAFT'::character varying, 'PENDING_REVIEW'::character varying, 'PUBLISHED'::character varying, 'REJECTED'::character varying])::text[]))),
    CONSTRAINT resources_type_check CHECK (((type)::text = ANY ((ARRAY['ARTICLE'::character varying, 'VIDEO'::character varying, 'PROBLEM_SET'::character varying, 'COURSE'::character varying])::text[])))
);

ALTER TABLE public.resources ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.resources_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.school_classes (
    id bigint NOT NULL,
    name character varying(255) NOT NULL
);

ALTER TABLE public.school_classes ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.school_classes_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.sections (
    id bigint NOT NULL,
    name character varying(255) NOT NULL,
    school_class_id bigint NOT NULL
);

ALTER TABLE public.sections ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.sections_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.students (
    id bigint NOT NULL,
    admission_number character varying(255) NOT NULL,
    parent_user_id bigint,
    section_id bigint NOT NULL,
    user_id bigint NOT NULL
);

ALTER TABLE public.students ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.students_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.subjects (
    id bigint NOT NULL,
    code character varying(255) NOT NULL,
    name character varying(255) NOT NULL
);

ALTER TABLE public.subjects ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.subjects_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.teachers (
    id bigint NOT NULL,
    employee_code character varying(255),
    user_id bigint NOT NULL
);

ALTER TABLE public.teachers ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.teachers_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.users (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    email character varying(255) NOT NULL,
    enabled boolean NOT NULL,
    full_name character varying(255) NOT NULL,
    password character varying(255) NOT NULL,
    role character varying(255) NOT NULL,
    subscription_tier character varying(255) NOT NULL,
    CONSTRAINT users_role_check CHECK (((role)::text = ANY ((ARRAY['ADMIN'::character varying, 'TEACHER'::character varying, 'STUDENT'::character varying, 'PARENT'::character varying, 'LEARNER'::character varying])::text[]))),
    CONSTRAINT users_subscription_tier_check CHECK (((subscription_tier)::text = ANY ((ARRAY['FREE'::character varying, 'PREMIUM'::character varying])::text[])))
);

ALTER TABLE public.users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.ai_usage_log
    ADD CONSTRAINT ai_usage_log_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.attendance
    ADD CONSTRAINT attendance_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.exams
    ADD CONSTRAINT exams_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.marks
    ADD CONSTRAINT marks_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.resource_views
    ADD CONSTRAINT resource_views_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.resources
    ADD CONSTRAINT resources_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.school_classes
    ADD CONSTRAINT school_classes_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.sections
    ADD CONSTRAINT sections_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.students
    ADD CONSTRAINT students_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.subjects
    ADD CONSTRAINT subjects_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.teachers
    ADD CONSTRAINT teachers_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.students
    ADD CONSTRAINT uk4ijilwehsq4n3vhrdlq722lnc UNIQUE (admission_number);

ALTER TABLE ONLY public.users
    ADD CONSTRAINT uk6dotkott2kjsp8vw4d0m25fb7 UNIQUE (email);

ALTER TABLE ONLY public.teachers
    ADD CONSTRAINT ukcd1k6xwg9jqtiwx9ybnxpmoh9 UNIQUE (user_id);

ALTER TABLE ONLY public.marks
    ADD CONSTRAINT ukclhxmbpph0wfgle41hr6wnns1 UNIQUE (exam_id, student_id);

ALTER TABLE ONLY public.attendance
    ADD CONSTRAINT ukfh0r5sfdt16udyw5quf5syvwh UNIQUE (student_id, date);

ALTER TABLE ONLY public.students
    ADD CONSTRAINT ukg4fwvutq09fjdlb4bb0byp7t UNIQUE (user_id);

ALTER TABLE ONLY public.ai_usage_log
    ADD CONSTRAINT ukig5ifb7r4yotucbkaf8bh9l2 UNIQUE (user_id, date);

ALTER TABLE ONLY public.subjects
    ADD CONSTRAINT ukrg7x1lyii7kdyycw98d45vep5 UNIQUE (code);

ALTER TABLE ONLY public.resource_views
    ADD CONSTRAINT uktks1rqnvsmhmcnnnwhoryib55 UNIQUE (user_id, resource_id);

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.exams
    ADD CONSTRAINT fk1ffpss7gx7g6y8d9q3d9acvsk FOREIGN KEY (school_class_id) REFERENCES public.school_classes(id);

ALTER TABLE ONLY public.ai_usage_log
    ADD CONSTRAINT fk2kfwnc2d59fw4778qfjqiydop FOREIGN KEY (user_id) REFERENCES public.users(id);

ALTER TABLE ONLY public.resources
    ADD CONSTRAINT fk4pw8txf3qlb47u8fwgwhn9se5 FOREIGN KEY (author_id) REFERENCES public.users(id);

ALTER TABLE ONLY public.marks
    ADD CONSTRAINT fk6o5buy4g7i65v20hjy9inwn05 FOREIGN KEY (student_id) REFERENCES public.students(id);

ALTER TABLE ONLY public.attendance
    ADD CONSTRAINT fk7121lveuhtmu9wa6m90ayd5yg FOREIGN KEY (student_id) REFERENCES public.students(id);

ALTER TABLE ONLY public.teachers
    ADD CONSTRAINT fkb8dct7w2j1vl1r2bpstw5isc0 FOREIGN KEY (user_id) REFERENCES public.users(id);

ALTER TABLE ONLY public.students
    ADD CONSTRAINT fkbu72kq4xd8qjcemytgfxel71l FOREIGN KEY (section_id) REFERENCES public.sections(id);

ALTER TABLE ONLY public.students
    ADD CONSTRAINT fkdt1cjx5ve5bdabmuuf3ibrwaq FOREIGN KEY (user_id) REFERENCES public.users(id);

ALTER TABLE ONLY public.students
    ADD CONSTRAINT fkhsjm3ph325lh964nldepo9evf FOREIGN KEY (parent_user_id) REFERENCES public.users(id);

ALTER TABLE ONLY public.resource_views
    ADD CONSTRAINT fkn9rfdwflfa1gdaufr32uwrags FOREIGN KEY (resource_id) REFERENCES public.resources(id);

ALTER TABLE ONLY public.exams
    ADD CONSTRAINT fkopre4n7j7fpxqbtbwpv8ywn1y FOREIGN KEY (subject_id) REFERENCES public.subjects(id);

ALTER TABLE ONLY public.sections
    ADD CONSTRAINT fkpxpbk38aktd71xg1vkq69cvhj FOREIGN KEY (school_class_id) REFERENCES public.school_classes(id);

ALTER TABLE ONLY public.marks
    ADD CONSTRAINT fkqsh7nyinh5ntyjr023na0qfaa FOREIGN KEY (exam_id) REFERENCES public.exams(id);

ALTER TABLE ONLY public.resource_views
    ADD CONSTRAINT fksnvy095s1417ak8mwubssmwbc FOREIGN KEY (user_id) REFERENCES public.users(id);
