-- Forgot-password flow (ROADMAP.md — auth improvements). One row per reset request, not a
-- field on users: a user can request multiple resets, and old tokens need to stay invalid
-- without being deleted (kept for audit/rate-limiting purposes later if needed).

CREATE TABLE password_reset_tokens (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    token VARCHAR(255) NOT NULL UNIQUE,
    user_id BIGINT NOT NULL REFERENCES users(id),
    expires_at TIMESTAMP(6) NOT NULL,
    used BOOLEAN NOT NULL,
    created_at TIMESTAMP(6)
);

CREATE INDEX idx_password_reset_tokens_user_id ON password_reset_tokens(user_id);
