CREATE TABLE lessons (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    summary VARCHAR(255) NOT NULL,
    concept TEXT NOT NULL,
    grade INTEGER,
    subject VARCHAR(255),
    source_year INTEGER,
    author_id BIGINT NOT NULL REFERENCES users(id),
    status VARCHAR(255) NOT NULL CHECK (status IN ('DRAFT','PENDING_REVIEW','PUBLISHED','REJECTED')),
    review_note VARCHAR(255),
    created_at TIMESTAMP(6) WITHOUT TIME ZONE
);

CREATE TABLE lesson_questions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    lesson_id BIGINT NOT NULL REFERENCES lessons(id) ON DELETE CASCADE,
    position INTEGER NOT NULL,
    prompt TEXT NOT NULL,
    correct_answer VARCHAR(500) NOT NULL,
    hint VARCHAR(500),
    explanation TEXT
);

CREATE TABLE lesson_question_options (
    lesson_question_id BIGINT NOT NULL REFERENCES lesson_questions(id) ON DELETE CASCADE,
    option_text VARCHAR(500) NOT NULL,
    position INTEGER NOT NULL
);
