ALTER TABLE lesson_questions ADD COLUMN difficulty VARCHAR(20) NOT NULL DEFAULT 'BEGINNER';

ALTER TABLE users ADD COLUMN points INTEGER NOT NULL DEFAULT 0;

CREATE TABLE lesson_attempts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id),
    lesson_id BIGINT NOT NULL REFERENCES lessons(id),
    lesson_question_id BIGINT NOT NULL REFERENCES lesson_questions(id),
    selected_answer TEXT,
    correct BOOLEAN NOT NULL,
    points_awarded INTEGER NOT NULL,
    attempted_at TIMESTAMP(6) NOT NULL DEFAULT now()
);

CREATE INDEX idx_lesson_attempts_user_id ON lesson_attempts(user_id);
